[package]
name = "openai"
version = "0.1.0"
authors = ["Andrew <andrew@subarctic.org>"]

[dependencies]
glob = "*"
image = "*"
rand = "*"
hyper = ">=0.7, <0.10"
vnc = "0.4"
rustc-serialize = "*"
x11 = "2.3"

[dependencies.websocket]
git = "https://github.com/cyderize/rust-websocket.git"
